name: Language Statistics

on:
    schedule:
        - cron: "0 0 * * 1"
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.13

            - name: Install dependencies
              run: pip install requests

            - name: Run update script
              env: 
                GH_TOKEN: ${{ secrets.GH_LANG_TOKEN }}
              run: python scripts/language_stats.py

            - name: Push README.md changes
              run: |
                git status
                git add .
                git diff
                git config --global user.email "github-actions-bot@andrew6rant.github.io"
                git config --global user.name "Andrew6rant/GitHub-Actions-Bot"
                git commit -m "Updated README" -a || echo "No changes to commit"
                git pull
                git push origin main
